// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Construccion.Entities.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Construccion.DataAccess.Context
{
    public partial class ConstruccionContext : DbContext
    {
        public ConstruccionContext()
        {
        }

        public ConstruccionContext(DbContextOptions<ConstruccionContext> options)
            : base(options)
        {
        }

        public virtual DbSet<WW_tbRoles> WW_tbRoles { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<WW_tbRoles>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("WW_tbRoles");

                entity.Property(e => e.role_Id).ValueGeneratedOnAdd();

                entity.Property(e => e.role_Nombre)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.role_Id)
                    .HasName("PK_Acce_tbRoles_role_Id");

                entity.ToTable("tbRoles", "Acce");

                entity.Property(e => e.role_Estado)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.role_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.role_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.role_Nombre)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}