// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int carg_Id { get; set; }
        public string carg_Cargo { get; set; }
        public int? user_UsuCreacion { get; set; }
        public DateTime carg_FechaCreacion { get; set; }
        public int? user_IdModificacion { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }

        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}