// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime depa_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? depa_FechaModificacion { get; set; }

        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}