// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbEmpleadosPorConstruccion
    {
        public int emco_Id { get; set; }
        public int cons_Id { get; set; }
        public int empl_Id { get; set; }
        [NotMapped]
        public string empl_Nombre { get; set; }
        [NotMapped]
        public string empl_Apellidos { get; set; }
        [NotMapped]
        public string empl_Telefono { get; set; }
        [NotMapped]
        public string empl_CorreoEletronico { get; set; }
        public int? user_UsuCreacion { get; set; }
        public DateTime cons_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? cons_FechaModificacion { get; set; }
        public bool? cons_Estado { get; set; }

        public virtual tbConstrucciones cons { get; set; }
        public virtual tbEmpleados empl { get; set; }
    }
}