// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbEmpleadosPorConstruccion = new HashSet<tbEmpleadosPorConstruccion>();
        }

        public int empl_Id { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombre { get; set; }
        public string empl_Apellidos { get; set; }
        public string empl_Sexo { get; set; }
        public string esta_ID { get; set; }
        public string muni_Id { get; set; }
        public int carg_Id { get; set; }
        [NotMapped]
        public string carg_Cargo { get; set; }
        public string empl_DireccionExacta { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_Telefono { get; set; }
        public string empl_CorreoEletronico { get; set; }
        public int user_IdCreacion { get; set; }
        public DateTime empl_FechaCreacion { get; set; }
        public int? user_IdModificacion { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }

        public virtual tbCargos carg { get; set; }
        public virtual tbEstadosCiviles esta { get; set; }
        public virtual ICollection<tbEmpleadosPorConstruccion> tbEmpleadosPorConstruccion { get; set; }
    }
}