// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public string esta_ID { get; set; }
        public string esta_Descripcion { get; set; }
        public int user_IdCreacion { get; set; }
        public DateTime esta_FechaCrea { get; set; }
        public int? user_IdModificacion { get; set; }
        public DateTime? esta_FechaModi { get; set; }

        public virtual tbUsuarios user_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios user_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}