// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbInsumos
    {
        public tbInsumos()
        {
            tbInsumosConstruccion = new HashSet<tbInsumosConstruccion>();
        }

        public int insm_Id { get; set; }
        public string insm_Descripcion { get; set; }
        public int unim_Id { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime insm_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? insm_FechaModificacion { get; set; }
        public bool? user_Estado { get; set; }

        [NotMapped]
        public string unim_Descripcion { get; set; }

        public virtual tbUnidadesMedida unim { get; set; }
        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosConstruccion> tbInsumosConstruccion { get; set; }
    }
}