// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbIncidencia
    {
        public int inci_Id { get; set; }
        public int cons_Id { get; set; }
        public string inci_Descripcion { get; set; }
        public int? user_UsuCreacion { get; set; }
        public DateTime inci_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? inci_FechaModificacion { get; set; }
        public bool? user_Estado { get; set; }

        public virtual tbConstrucciones cons { get; set; }
        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
    }
}