// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbClientes = new HashSet<tbClientes>();
            tbConstrucciones = new HashSet<tbConstrucciones>();
        }

        public string muni_id { get; set; }
        public string muni_Nombre { get; set; }
        public string depa_Id { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime muni_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }

        public virtual tbDepartamentos depa { get; set; }
        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbConstrucciones> tbConstrucciones { get; set; }
    }
}