// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbPantallas
    {
        public tbPantallas()
        {
            tbPantallasRoles = new HashSet<tbPantallasRoles>();
        }

        public int pant_Id { get; set; }
        public string pant_Nombre { get; set; }
        public string pant_URL { get; set; }
        public string pant_Menu { get; set; }
        public string pant_HtmlId { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime pant_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? pant_FechaModificacion { get; set; }
        public bool? pant_Estado { get; set; }

        [NotMapped]
        public int role_Id { get; set; }

        [NotMapped]
        public bool esAdmin { get; set; }

        public virtual ICollection<tbPantallasRoles> tbPantallasRoles { get; set; }
    }
}