// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbPantallasRoles = new HashSet<tbPantallasRoles>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int role_Id { get; set; }
        public string role_Nombre { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime role_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? role_FechaModificacion { get; set; }
        public bool? role_Estado { get; set; }
        [NotMapped]
        public int pant_Id { get; set; }
        [NotMapped]
        public string pant_Nombre { get; set; }


        public virtual ICollection<tbPantallasRoles> tbPantallasRoles { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}