// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseuser_UsuCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseuser_UsuModificacionNavigation = new HashSet<tbUsuarios>();
            tbDepartamentosuser_UsuCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosuser_UsuModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEstadosCivilesuser_IdCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesuser_IdModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbInsumosConstruccionuser_UsuCreacionNavigation = new HashSet<tbInsumosConstruccion>();
            tbInsumosConstruccionuser_UsuModificacionNavigation = new HashSet<tbInsumosConstruccion>();
            tbInsumosuser_UsuCreacionNavigation = new HashSet<tbInsumos>();
            tbInsumosuser_UsuModificacionNavigation = new HashSet<tbInsumos>();
            tbMunicipiosuser_UsuCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosuser_UsuModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasRolesuser_UsuCreacionNavigation = new HashSet<tbPantallasRoles>();
            tbPantallasRolesuser_UsuModificacionNavigation = new HashSet<tbPantallasRoles>();
            tbUnidadesMedidauser_UsuCreacionNavigation = new HashSet<tbUnidadesMedida>();
            tbUnidadesMedidauser_UsuModificacionNavigation = new HashSet<tbUnidadesMedida>();
        }

        public int user_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public string user_Contrasena { get; set; }
        public bool? user_EsAdmin { get; set; }
        public int? role_Id { get; set; }
        public int? empe_Id { get; set; }
        [NotMapped]
        public string empl_Nombre { get; set; }
        public int? user_UsuCreacion { get; set; }
        public DateTime user_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? user_FechaModificacion { get; set; }
        public bool? user_Estado { get; set; }

        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesuser_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesuser_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosConstruccion> tbInsumosConstruccionuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbInsumosConstruccion> tbInsumosConstruccionuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumosuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumosuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasRoles> tbPantallasRolesuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasRoles> tbPantallasRolesuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbUnidadesMedida> tbUnidadesMedidauser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbUnidadesMedida> tbUnidadesMedidauser_UsuModificacionNavigation { get; set; }
    }
}