// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class VW_tbUnidadesMedida
    {
        public int unim_Id { get; set; }
        public string unim_Descripcion { get; set; }
    }
}