// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class VW_tbInsumos
    {
        public int insm_Id { get; set; }
        public string insm_Descripcion { get; set; }
    }
}