// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class VW_tbClientes
    {
        public int clie_Id { get; set; }
        public string clie_Nombre { get; set; }
        public string clie_Identificacion { get; set; }
        public string clie_Telefono { get; set; }
        public string clie_CorreoElectronico { get; set; }
        public string depa_Nombre { get; set; }
        public string muni_Nombre { get; set; }
        public string clie_DireccionExacta { get; set; }
    }
}