// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class VW_tbConstrucciones
    {
        public int cons_Id { get; set; }
        public string cons_Proyecto { get; set; }
        public string cons_ProyectoDescripcion { get; set; }
        public string depa_Nombre { get; set; }
        public string muni_Nombre { get; set; }
        public string cons_Direccion { get; set; }
        public DateTime? cons_FechaInicio { get; set; }
        public DateTime? cons_FechaFin { get; set; }
    }
}