// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class VW_tbEmpleados
    {
        public int empl_Id { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombre { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public string empl_CorreoEletronico { get; set; }
        public string carg_Cargo { get; set; }
        public string empl_DireccionExacta { get; set; }
    }
}