// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class WV_tbUsuarios
    {
        public int user_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public string role_Nombre { get; set; }
        public string Es_Admin { get; set; }
    }
}