// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class WV_tbPantallas
    {
        public int pant_Id { get; set; }
        public string pant_Nombre { get; set; }
        public string pant_Menu { get; set; }
        public string pant_URL { get; set; }
    }
}