// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Construccion.Entities.Entities
{
    public partial class WW_tbRoles
    {
        public int role_Id { get; set; }
        public string role_Nombre { get; set; }
    }
}